---
sidebar: sidebar 
permalink: legal-notices.html 
keywords: copyrights, notice, trademarks, patents, privacy, open source 
summary: Avisos legais fornecem acesso a declarações de direitos autorais, marcas registradas, patentes e muito mais. 
---
= Avisos legais
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


Avisos legais fornecem acesso a declarações de direitos autorais, marcas registradas, patentes e muito mais.



[[copyright]]
== Direitos de autor

https://www.netapp.com/company/legal/copyright/["https://www.netapp.com/company/legal/copyright/"^]



[[trademarks]]
== Marcas comerciais

NetApp, o logotipo DA NetApp e as marcas listadas na página de marcas comerciais da NetApp são marcas comerciais da NetApp, Inc. Outros nomes de produtos e empresas podem ser marcas comerciais de seus respetivos proprietários.

https://www.netapp.com/company/legal/trademarks/["https://www.netapp.com/company/legal/trademarks/"^]



[[patents]]
== Patentes

Uma lista atual de patentes de propriedade da NetApp pode ser encontrada em:

https://www.netapp.com/pdf.html?item=/media/11887-patentspage.pdf["https://www.netapp.com/pdf.html?item=/media/11887-patentspage.pdf"^]



[[privacy-policy]]
== Política de privacidade

https://www.netapp.com/company/legal/privacy-policy/["https://www.netapp.com/company/legal/privacy-policy/"^]



[[machine-translation]]
== Tradução de máquina

Informações importantes sobre conteúdo localizado.

https://www.netapp.com/company/legal/machine-translation/["https://www.netapp.com/company/legal/machine-translation/"^]



[[open-source]]
== Código aberto

Fornece informações sobre direitos autorais de terceiros e licenças usadas neste produto. O seu produto não utiliza necessariamente todos os componentes de software referidos abaixo.

https://library.netapp.com/ecm/ecm_download_file/ECMLP2880727["Aviso para SnapCenter 4,6"^]
