---
permalink: concept/reference_data_security.html 
sidebar: sidebar 
keywords: security,authentication, CA certificates 
summary: A SnapCenter emprega recursos rígidos de segurança e autenticação para permitir que você mantenha seus dados seguros. 
---
= Recursos de segurança
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A SnapCenter emprega recursos rígidos de segurança e autenticação para permitir que você mantenha seus dados seguros.

O SnapCenter inclui os seguintes recursos de segurança:

* Toda a comunicação com o SnapCenter usa HTTP sobre SSL (HTTPS).
* Todas as credenciais no SnapCenter são protegidas usando criptografia AES (Advanced Encryption Standard).
* O SnapCenter usa algoritmos de segurança compatíveis com o padrão Federal de processamento de informações (FIPS).
* O SnapCenter suporta o uso dos certificados de CA autorizados fornecidos pelo cliente.
* O SnapCenter 4.1.1 ou posterior suporta a comunicação TLS (Transport Layer Security) 1,2 com o ONTAP. Você também pode usar a comunicação TLS 1,2 entre clientes e servidores.
* O SnapCenter é instalado no firewall da sua empresa para permitir o acesso ao servidor SnapCenter e para permitir a comunicação entre o servidor SnapCenter e os plug-ins.
* O acesso à API e à operação do SnapCenter usa tokens criptografados com criptografia AES, que expiram após 24 horas.
* O SnapCenter é integrado ao Windows active Directory para login e controle de acesso baseado em função (RBAC) que regem as permissões de acesso.
* Os cmdlets do SnapCenter PowerShell são protegidos por sessão.
* Após um período padrão de 15 minutos de inatividade, o SnapCenter avisa que você será desconetado em 5 minutos. Após 20 minutos de inatividade, o SnapCenter faz o logout e você deve fazer login novamente. Você pode modificar o período de logout.
* O início de sessão está temporariamente desativado após 5 ou mais tentativas de início de sessão incorretas.




== Visão geral do certificado CA

O instalador do servidor SnapCenter permite o suporte centralizado de certificados SSL durante a instalação. Para melhorar a comunicação segura entre o servidor e o plug-in, o SnapCenter suporta o uso dos certificados de CA autorizados fornecidos pelo cliente.

Você deve implantar certificados de CA depois de instalar o servidor SnapCenter e os respetivos plug-ins. Para obter mais informações, link:../install/reference_generate_CA_certificate_CSR_file.html["Gerar arquivo CSR do certificado CA"^]consulte .

Você também pode implantar o certificado CA para o plug-in SnapCenter para VMware vSphere. Para obter mais informações, consulte  https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_create_and_import_certificates.html["Criar e importar certificados"^] .
